import type { ConceptErrorTag } from '../types';

export const errorCatalog: Record<ConceptErrorTag, string> = {
  no_reconoce_inmediato: 'No interpreta correctamente un dato inmediato.',
  confunde_endianness_registro: 'Invierte bytes dentro del registro sin corresponder.',
  invierte_fuente_destino: 'Confunde el orden destino, fuente.',
  cree_mov_borra_fuente: 'Cree que MOV elimina el valor de la fuente.',
  confunde_cl_ch: 'Confunde byte bajo CL con byte alto CH.',
  cree_byte_no_afecta_registro: 'No entiende que CL forma parte de CX.',
  cree_ah_borra_al: 'Cree que modificar AH borra AL.',
  confunde_ah_al: 'Confunde byte alto AH con byte bajo AL.',
  cree_copia_ax_completo: 'Cree que MOV DL, AL copia AX completo.',
  confunde_little_endian: 'Confunde el orden de bytes en memoria.',
  no_comprende_dw_16_bits: 'No identifica que DW reserva una palabra de 16 bits.',
  confunde_etiqueta_con_direccion: 'Cree que la etiqueta representa solo la dirección, no el contenido asociado.',
  confunde_bytes_con_valor_logico: 'Interpreta los bytes físicos como si fueran el valor lógico cargado.',
  add_reemplaza_destino: 'Cree que ADD reemplaza el destino con la fuente.',
  add_no_modifica_destino: 'Cree que ADD no modifica AX.',
  confunde_inmediato_con_memoria: 'Confunde un literal inmediato con una etiqueta de memoria.',
  confunde_inmediato_con_registro: 'Confunde un literal inmediato con un registro.',
  sub_no_modifica_destino: 'Cree que SUB no modifica AX.',
  sub_reemplaza_destino: 'Cree que SUB reemplaza AX con el inmediato.',
  mov_borra_fuente: 'Cree que MOV borra el registro fuente.',
  no_reconoce_escritura_memoria: 'No reconoce que MOV word R, AX escribe en memoria.',
  pierde_byte_alto: 'No conserva el byte alto al representar una palabra.',
  cree_dw_avanza_1: 'Cree que cada elemento DW avanza un byte en lugar de dos.',
  salta_un_elemento: 'Calcula la dirección como si saltara un elemento completo adicional.',
  confunde_offset_con_contenido: 'Confunde offset ARR con el contenido almacenado en ARR.',
  confunde_offset_con_bytes: 'Confunde la dirección con la representación física de bytes.',
  confunde_si_con_contenido: 'Confunde SI con [SI]; usa el valor del registro en vez del contenido apuntado.',
  cree_add_si_1_apunta_siguiente: 'Cree que avanzar SI en 1 llega al siguiente elemento DW.',
  no_reconoce_lectura_desalineada: 'No reconoce que una lectura desde una dirección intermedia produce una palabra incorrecta.',
  avance_si_incorrecto_1: 'Avanza SI en 1 byte aunque el arreglo usa palabras DW.',
  avance_si_incorrecto_4: 'Avanza SI demasiado y salta un elemento.',
  bx_no_recibe_si: 'No reconoce que MOV BX, SI copia el valor de SI en BX.',
  avance_bx_incorrecto_1: 'Avanza BX en 1 byte aunque el arreglo usa palabras DW.',
  avance_bx_no_cambia: 'Cree que ADD BX, 2 no modifica BX.',
  confunde_bx_con_bx_indirecto: 'Confunde BX con [BX]; suma la dirección en vez del contenido apuntado.',
  no_reconoce_offset_sum: 'No reconoce que offset SUM carga la dirección de SUM.',
  confunde_di_con_contenido_sum: 'Confunde DI con el contenido almacenado en SUM.',
  no_reconoce_escritura_indirecta: 'No reconoce que MOV word [DI], AX escribe en la memoria apuntada por DI.',
  escribe_en_di_no_memoria: 'Cree que la instrucción modifica DI en vez de la memoria apuntada.'
};
