import type { ConceptErrorTag } from '../types';

export const errorCatalog: Record<ConceptErrorTag, string> = {
  no_reconoce_inmediato: 'No interpreta correctamente un dato inmediato.',
  confunde_endianness_registro: 'Invierte bytes dentro del registro sin corresponder.',
  invierte_fuente_destino: 'Confunde el orden destino, fuente.',
  cree_mov_borra_fuente: 'Cree que MOV elimina el valor de la fuente.',
  confunde_cl_ch: 'Confunde byte bajo CL con byte alto CH.',
  cree_byte_no_afecta_registro: 'No entiende que CL forma parte de CX.',
  cree_ah_borra_al: 'Cree que modificar AH borra AL.',
  confunde_ah_al: 'Confunde byte alto AH con byte bajo AL.',
  cree_copia_ax_completo: 'Cree que MOV DL, AL copia AX completo.',
  confunde_little_endian: 'Confunde el orden de bytes en memoria.',
  no_comprende_dw_16_bits: 'No identifica que DW reserva una palabra de 16 bits.',
  confunde_etiqueta_con_direccion: 'Cree que la etiqueta representa solo la dirección, no el contenido asociado.',
  confunde_bytes_con_valor_logico: 'Interpreta los bytes físicos como si fueran el valor lógico cargado.',
  add_reemplaza_destino: 'Cree que ADD reemplaza el destino con la fuente.',
  add_no_modifica_destino: 'Cree que ADD no modifica AX.',
  confunde_inmediato_con_memoria: 'Confunde un literal inmediato con una etiqueta de memoria.',
  confunde_inmediato_con_registro: 'Confunde un literal inmediato con un registro.',
  sub_no_modifica_destino: 'Cree que SUB no modifica AX.',
  sub_reemplaza_destino: 'Cree que SUB reemplaza AX con el inmediato.',
  mov_borra_fuente: 'Cree que MOV borra el registro fuente.',
  no_reconoce_escritura_memoria: 'No reconoce que MOV word R, AX escribe en memoria.',
  pierde_byte_alto: 'No conserva el byte alto al representar una palabra.',
  cree_dw_avanza_1: 'Cree que cada elemento DW avanza un byte en lugar de dos.',
  salta_un_elemento: 'Calcula la dirección como si saltara un elemento completo adicional.',
  confunde_offset_con_contenido: 'Confunde offset ARR con el contenido almacenado en ARR.',
  confunde_offset_con_bytes: 'Confunde la dirección con la representación física de bytes.',
  confunde_si_con_contenido: 'Confunde SI con [SI]; usa el valor del registro en vez del contenido apuntado.',
  cree_add_si_1_apunta_siguiente: 'Cree que avanzar SI en 1 llega al siguiente elemento DW.',
  no_reconoce_lectura_desalineada: 'No reconoce que una lectura desde una dirección intermedia produce una palabra incorrecta.',
  avance_si_incorrecto_1: 'Avanza SI en 1 byte aunque el arreglo usa palabras DW.',
  avance_si_incorrecto_4: 'Avanza SI demasiado y salta un elemento.',
  bx_no_recibe_si: 'No reconoce que MOV BX, SI copia el valor de SI en BX.',
  avance_bx_incorrecto_1: 'Avanza BX en 1 byte aunque el arreglo usa palabras DW.',
  avance_bx_no_cambia: 'Cree que ADD BX, 2 no modifica BX.',
  confunde_bx_con_bx_indirecto: 'Confunde BX con [BX]; suma la dirección en vez del contenido apuntado.',
  no_reconoce_offset_sum: 'No reconoce que offset SUM carga la dirección de SUM.',
  confunde_di_con_contenido_sum: 'Confunde DI con el contenido almacenado en SUM.',
  no_reconoce_escritura_indirecta: 'No reconoce que MOV word [DI], AX escribe en la memoria apuntada por DI.',
  escribe_en_di_no_memoria: 'Cree que la instrucción modifica DI en vez de la memoria apuntada.',
  no_reconoce_zf: "No reconoce que ZF se activa cuando el resultado es cero.",
  zf_se_activa_sin_cero: "Cree que ZF se activa aunque el resultado no sea cero.",
  no_reconoce_cf: "No reconoce acarreo en suma de 16 bits.",
  confunde_cf_con_of: "Confunde acarreo sin signo con overflow con signo.",
  no_reconoce_wraparound: "No reconoce que FFFFh + 1 produce 0000h en 16 bits.",
  no_reconoce_sf: "No reconoce que SF se activa cuando el bit más significativo del resultado es 1.",
  confunde_negativo_decimal: "Interpreta el resultado sin considerar complemento a dos.",
  inc_modifica_cf: "Cree que INC modifica CF.",
  inc_no_modifica_destino: "Cree que INC no modifica el destino.",
  dec_modifica_cf: "Cree que DEC modifica CF.",
  dec_no_reconoce_zf: "No reconoce que DEC puede producir cero y activar ZF.",
  cmp_modifica_ax: "Cree que CMP guarda la resta en AX.",
  cmp_no_modifica_flags: "Cree que CMP no modifica banderas.",
  cmp_confunde_resultado: "Confunde el resultado interno de comparación con un valor guardado.",
  no_reconoce_pf: "No reconoce la bandera de paridad para el byte bajo.",
  pf_confunde_bits_uno: "Calcula mal la paridad del byte bajo.",
  no_reconoce_of: "No reconoce overflow con signo.",
  of_confunde_con_cf: "Confunde OF con CF en aritmética con signo.",
  cmp_modifica_registros: "Cree que CMP guarda la resta modificando AX o BX.",
  no_reconoce_zf_igual: "No reconoce que ZF = 1 cuando la comparación da igualdad.",
  no_reconoce_zf_diferente: "No reconoce que ZF = 0 cuando los valores son distintos.",
  jz_compara_por_si_mismo: "Cree que JZ compara por sí mismo.",
  jz_ignora_flags: "No reconoce que JZ depende de ZF generado previamente.",
  salto_sin_flags_previos: "No reconoce que un salto condicional necesita flags preparados antes.",
  invierte_mayor_menor: "Invierte la relación mayor/menor después de CMP.",
  no_reconoce_jg: "No reconoce la condición de JG: ZF = 0 y SF = OF.",
  no_reconoce_jl: "No reconoce la condición de JL: SF ≠ OF.",
  confunde_cf_con_signed: "Usa CF para decidir comparación con signo en JG/JL.",
  no_reconoce_label_ejecutada: "No identifica la etiqueta ejecutada después del salto.",
  no_reconoce_jmp_fin: "No reconoce que JMP fin evita caer en otras etiquetas.",
  no_reconoce_flujo_secuencial: "No reconoce que, sin salto, la CPU continúa con la siguiente instrucción en orden.",
  cree_salto_a_direccion_fisica: "Cree que el salto va a una dirección física, no a una etiqueta didáctica.",
  no_reconoce_escritura_resultado: "No reconoce que la etiqueta ejecutada escribe el resultado en memoria.",
  cx_no_es_contador: "No reconoce que CX controla la cantidad de iteraciones.",
  loop_no_decrementa_cx: "Cree que LOOP no decrementa CX.",
  loop_no_depende_de_cx: "Cree que LOOP salta sin revisar CX.",
  loop_saltea_primera: "Cree que LOOP evita ejecutar la primera iteración.",
  si_no_apunta_arreglo: "No reconoce que SI debe apuntar al inicio del arreglo.",
  confunde_si_con_si_indirecto: "Confunde SI con [SI]; usa la dirección como dato.",
  add_reemplaza_ax: "Cree que ADD reemplaza AX por el valor leído.",
  add_no_modifica_ax: "Cree que ADD no modifica AX.",
  cx_no_cambia_en_loop: "Cree que CX no cambia durante LOOP.",
  cx_decrementa_antes_de_cuerpo: "Confunde el momento en que LOOP decrementa CX.",
  suma_final_incorrecta: "Calcula incorrectamente la suma final del arreglo.",
  si_final_incorrecto: "Calcula incorrectamente el SI final después de 4 palabras.",
  c_equivale_run: "Confunde la equivalencia en C con una ejecución automática sin control.",
  confunde_suma_con_avance_indice: "Confunde la suma del acumulador con el avance del índice del arreglo.",
  defensa_dw_1_byte: "Cree que DW ocupa un byte.",
  defensa_no_relaciona_dw_si: "No relaciona el tamaño de DW con el avance de SI.",
  stack_crece_arriba: "Cree que la pila crece hacia direcciones mayores.",
  push_no_modifica_sp: "Cree que PUSH no modifica SP.",
  push_no_guarda_valor: "No reconoce que PUSH guarda el valor del registro en la pila.",
  confunde_sp_con_contenido: "Confunde la dirección en SP con el contenido almacenado en la pila.",
  cree_push_reemplaza_tope: "Cree que un segundo PUSH reemplaza el valor anterior en lugar de apilar encima.",
  cree_fifo: "Cree que la pila funciona como cola FIFO.",
  no_reconoce_lifo: "No reconoce el comportamiento LIFO: último en entrar, primero en salir.",
  pop_no_modifica_sp: "Cree que POP no modifica SP.",
  pop_no_carga_registro: "No reconoce que POP carga el valor del tope en el registro destino.",
  pop_confunde_registro_destino: "Confunde el registro destino del POP.",
  cree_pop_borra_toda_pila: "Cree que un POP vacía toda la pila.",
  sp_final_incorrecto: "Calcula incorrectamente el valor final de SP.",
  confunde_memoria_historica_con_pila_activa: "Confunde valores residuales en memoria con elementos activos de la pila.",
  defensa_fifo: "Sigue aplicando lógica FIFO en la defensa.",
  defensa_no_relaciona_tope: "No relaciona el primer POP con el elemento ubicado en el tope.",
  no_identifica_entrada: "No identifica AX como entrada/parámetro de la subrutina.",
  no_identifica_proceso: "No identifica ADD AX, AX como procesamiento de la subrutina.",
  no_identifica_salida: "No identifica AX como resultado de la subrutina.",
  call_modifica_ax_directamente: "Cree que CALL modifica AX por sí mismo.",
  call_no_transfiere_control: "No reconoce que CALL transfiere el control a la subrutina.",
  confunde_principal_con_subrutina: "No distingue entre flujo principal y procedimiento.",
  subrutina_ejecuta_sin_call: "Cree que la subrutina se ejecuta automáticamente aunque no haya CALL.",
  ret_no_vuelve_principal: "No reconoce que RET devuelve el control al programa principal.",
  ret_reinicia_programa: "Cree que RET reinicia el programa.",
  no_reconoce_instruccion_posterior_call: "No reconoce que después de RET se ejecuta la instrucción posterior a CALL.",
  bx_no_recibe_resultado: "No reconoce que MOV BX, AX guarda el resultado devuelto en AX.",
  confunde_call_con_jmp: "Confunde CALL con un salto sin retorno.",
  defensa_invertida: "Invierte la función de CALL y RET."
};
